### ISSUE TITLE
Feature Request: Reverse Workflow for Disposable Emails

### ISSUE THREAD

**Issue by illgitthat** [jessetinell/x2.email#4]
Thanks for publishing this!

## Feature Request:

Is it possible to add a reverse workflow for managing disposable emails? Instead of creating a new alias for each service, consider accepting all emails with a wildcard by default and blocking specific addresses as needed.

This would reduce the need to log in and create a new alias for every service beforehand, and still allow for targeted blocking of unwanted emails.

**Comment by jessetinell** [comment]
You can achieve this using Cloudflare and Gmail (and probably other email clients). 
in cloudflare you can create a catch-all forwarding. Then in Gmail you could just block or filter out specific emails. 

I use that method nowadays. Works like a charm. 

Of course, this method is not 100% “safe” since one could just change the email prefix to go around the filter/block.  

x2.email is better if one needs 100% control.
